import { pgTable, pgEnum, uuid, varchar, text, date, integer, timestamp, index, jsonb } from 'drizzle-orm/pg-core'
import { relations } from 'drizzle-orm'
import { currency } from '@/v2/parent-model'
import { uuidv7PK } from '@/shared/utils/id'
import { projectOwnerEnrollment } from './project-owner_enrollment.model'


export const projectTypeEnum = pgEnum('project_type_enum', [
  // Green Economy — PILOT (fully functional)
  'regenerative_agriculture',
  'renewable_energy',
  // Brown Economy — scaffolded only
  'waste_management',           // renamed from waste_management
  // Blue Economy — scaffolded only
  'water_projects',             // new
  'blue_carbon',                // kept
])
export const projectStageEnum  = pgEnum('project_stage_enum',  ['registration', 'active', 'verification', 'completed'])
export const projectStatusEnum = pgEnum('project_status_enum', ['draft', 'active', 'suspended', 'closed'])
export const sectorEnum = pgEnum('sector_enum', [
  'green_economy',   // Regen Agri + Renewable Energy — PILOT
  'brown_economy',   // formerly waste_management — scaffolded
  'blue_economy',    // formerly blue_carbon / water projects — scaffolded
])

/**
 * project
 * The core entity. project.code maps to CraftedClimate's CC-PROJECT-ID namespace.
 * This is the join key between Crevy's database and CraftedClimate's dMRV payloads.
 * Code format: PRJ-GH-2026-001 — generated by the application layer.
 */
export const project = pgTable('project', {
  id:            uuid('id').primaryKey().$defaultFn(uuidv7PK),
  code:          varchar('code', { length: 100 }).notNull().unique(),
  name:          varchar('name', { length: 255 }),  //project name is nullable due to naming fatigue, users were tired of naming projects
  projectType:   projectTypeEnum('project_type').notNull(),
  projectStage:  projectStageEnum('project_stage').notNull().default('registration'),
  projectStatus: projectStatusEnum('project_status').notNull().default('draft'),
  sector:        sectorEnum('sector').notNull().default('green_economy'),
  projectTags:   jsonb('project_tags').array(),     //tags like `['agroforestry', 'cover_cropping', 'rotational_grazing']` for marketplace display and context for CraftedClimate's deployment team.  
  region:        varchar('region', { length: 100 }).notNull(),
  country:       varchar('country', { length: 100 }).notNull(),
  startDate:     date('start_date').notNull(),
  endDate:       date('end_date'),
  currencyId:    integer('currency_id').notNull().references(() => currency.id, { onDelete: 'restrict' }),
  createdBy:     text('created_by').notNull(),  // FK → user.id
  createdAt:     timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt:     timestamp('updated_at', { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => [
  index('idx_project_type').on(t.projectType),
  index('idx_project_status').on(t.projectStatus),
  index('idx_project_code').on(t.code),
])

export const projectRelations = relations(project, ({ one, many }) => ({
  currency: one(currency, { fields: [project.currencyId], references: [currency.id] }),

  // M-to-M: one project → many project_owner_enrollment rows
  projectOwnerEnrollments: many(projectOwnerEnrollment),
}))