


import { pgTable, pgEnum, uuid, text, varchar, timestamp, jsonb } from 'drizzle-orm/pg-core'
import { relations } from 'drizzle-orm'
import { user } from '@/v2/parent-model'
import { uuidv7PK } from '@/shared/utils/id'


export const projectOwnerVerificationStatusEnum = pgEnum('project_owner_verification_status_enum', ['pending', 'verified', 'rejected'])

/**
 * project_owner
 * Extended profile for users whose role is project owner.
 * 1-to-1 with user (one user can have one project owner profile).
 * Stores verification status and payment channel details for payout disbursement.
 * code format: PO-GH-000001 — generated by the application layer.
 */
export const projectOwner = pgTable('project_owner', {
  id:                 uuid('id').primaryKey().$defaultFn(uuidv7PK),
  userId:             text('user_id').notNull().unique().references(() => user.id, { onDelete: 'cascade' }),
  code:               varchar('code', { length: 50 }).notNull().unique(),
  verificationStatus: projectOwnerVerificationStatusEnum('verification_status').notNull().default('pending'),
  onboardedBy:        text('onboarded_by').references(() => user.id, { onDelete: 'set null' }),
  onboardedAt:        timestamp('onboarded_at', { withTimezone: true }).notNull().defaultNow(),

  // Flexible payment details
  bankDetails: jsonb('bank_details').$type<{
    bankName: string;
    accountNumber: string;
    accountName?: string;
  }>(),
  
  momoDetails: jsonb('momo_details').$type<{
    network: string;
    number: string;
    accountName?: string;
  }>(),

  createdAt:          timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt:          timestamp('updated_at', { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
})

export const projectOwnerRelations = relations(projectOwner, ({ one }) => ({
  user: one(user, { fields: [projectOwner.userId], references: [user.id] }),
}))