import { pgTable, pgEnum, uuid, varchar, decimal, date, integer, text, timestamp, index } from 'drizzle-orm/pg-core'
import { relations } from 'drizzle-orm'

import { project } from '../../projects/models/project.model'
import { creditTransaction } from '../../credits/models/credit_transaction.model'


import { currency } from '../../deps/models/currency.model'
import { projectOwner } from '../../project_owners/models/project_owner.model'
import { uuidv7PK } from '@/shared/utils/id'

export const payoutMethodEnum = pgEnum('payout_method_enum', ['mobile_money', 'bank_transfer', 'cash'])
export const payoutStatusEnum = pgEnum('payout_status_enum', ['pending', 'completed', 'failed'])

/**
 * payout
 * Payment disbursements to farmers following a credit sale.
 * Triggered when credit_transaction.status transitions to 'completed' for a non-internal sale.
 * payment_ref format: PAY-2026-000001 — generated by the application layer.
 */
export const payout = pgTable('payout', {
  id:            uuid('id').primaryKey().$defaultFn(uuidv7PK),
  paymentRef:    varchar('payment_ref', { length: 100 }).notNull().unique(),  //auto-generate
  projectOwnerId:      uuid('project_owner_id').notNull().references(() => projectOwner.id,            { onDelete: 'restrict' }),
  projectId:     uuid('project_id').notNull().references(() => project.id,          { onDelete: 'restrict' }),
  transactionId: uuid('transaction_id').notNull().references(() => creditTransaction.id, { onDelete: 'restrict' }),
  payoutAmount:  decimal('payout_amount', { precision: 12, scale: 2 }).notNull(),
  currencyId:    integer('currency_id').notNull().references(() => currency.id,     { onDelete: 'restrict' }),
  payoutDate:    date('payout_date').notNull(),
  payoutMethod:  payoutMethodEnum('payout_method').notNull(),
  payoutStatus:  payoutStatusEnum('payout_status').notNull().default('pending'),
  notes:         text('notes'),
  createdAt:     timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt:     timestamp('updated_at', { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => [
  index('idx_payout_farmer').on(t.projectOwnerId),
  index('idx_payout_project').on(t.projectId),
  index('idx_payout_status').on(t.payoutStatus),
])

export const payoutRelations = relations(payout, ({ one }) => ({
  projectOwner:      one(projectOwner,            { fields: [payout.projectOwnerId],      references: [projectOwner.id] }),
  project:     one(project,           { fields: [payout.projectId],     references: [project.id] }),
  transaction: one(creditTransaction, { fields: [payout.transactionId], references: [creditTransaction.id] }),
  currency:    one(currency,          { fields: [payout.currencyId],    references: [currency.id] }),
}))